parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: dvpbundles
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: fr
    secret: 565ab6adc2c9c93e0673c3abd0e727a97ce8cd00
    database_path: null
